apiVersion: v1
kind: Service
metadata:
  name: cpp-app-service
spec:
  type: NodePort
  selector:
    app: cpp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Assuming app listens on 8080 (if it was a web server)
      nodePort: 30007
